--- # check this link for type info: https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_bridge/README.md
- ros_topic_name: "/x500/sensor/altimeter" # example of converting ROS topic to Gazebo topic
  gz_topic_name: "/x500/sensor/altimeter"
  ros_type_name: "ros_gz_interfaces/msg/Altimeter"
  gz_type_name: "gz.msgs.Altimeter"
  direction: ROS_TO_GZ

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS #
